[package]
name = "task"
version = "0.1.0"
edition = "2021"
authors = ["alpha-tango-kilo <git@heyatk.com>"]
readme = "../README.md"
license = "AGPL-3.0-only"
repository = "https://codeberg.org/alpha-tango-kilo/overseer"

[dependencies]
delay_timer = "0.11"
eyre = "0.6"
tracing = "0.1"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_yaml = "0.8"
thiserror = "1.0"

[dependencies.tokio]
version = "1.18"
features = [
    "fs",
    "rt",
]
